""" 
SYS2

Módulo que acessa as funcionalidades do sistema SYS2

Author: Juliano Kosloski - Automation Developer
Created: 07/07/2022 by Juliano Kosloski
"""

import dotenv
import os
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

class SYS2:
	
	_fileDict = { 
		"61" : "C:/TEMP/061.PRN",
		"68" : "C:/TEMP/068.PRN",
		"139" : "C:/TEMP/139.PRN",
		"83" : "C:/TEMP/083.PRN",
	} 
 
	def startDriver():
		"""
		Starts up the Chrome WebDriver config and returns a readied driver instance
		"""

		option = webdriver.ChromeOptions() 
		option.binary_location = "C:/Program Files/Google/Chrome/Application/chrome.exe"  
		driverService = Service('C:/WebDrivers/chromedriver.exe') #sets up a driver service 
		driver = webdriver.Chrome(service=driverService, options=option) #starts the driver
		
		return driver
		
	def __getCred__() -> tuple: 
		"""
		Gets appropriate credentials and returns them for in-class use
		"""

		dotenv.load_dotenv(dotenv.find_dotenv())
		sysLogin = os.environ.get("USER_SYS2")
		sysPassword = os.environ.get("PASS_SYS2")
				
		return sysLogin, sysPassword  
			  
	def getLogin(driver):
		"""
  		Takes a new driver instance and logs into a website
        
        params:
        driver: a WebDriver instance generated by other function
  		"""
    
		sysLogin, sysPassword = SYS2.__getCred__() 
  
		driver.get("https://genericurl/index.php")
		element = driver.find_element(By.ID,"fieldUser" )
		element.clear()
		element.send_keys(sysLogin)
		element = driver.find_element(By.ID,"fieldPassword" )
		element.clear()
		element.send_keys(sysPassword)
		element = driver.find_element(By.XPATH, "//input[@value='Entrar']")
		element.click()
	
	def getLink(driver, url :str = "", attempts = 1) -> None:
		"""
		Navigates to a link on the web
  
		params:
		driver: a WebDriver instance generated by other function
		url: a string link to a webpage
		attempts: int of how many access tries
		"""

		tries = 0  
		while tries < attempts: #try to access the website x times
			driver.get(url)
			tries += 1
  
	def uploadFiles(driver):
		"""
		Navigates to the upload page, attaches files, and clicks the buttom to import
  
		params:
		driver: a WebDriver instance generated by other function
  		"""

		driver.get("https://url.com")
  
		print('Realizando importações...')

		for report in SYS2._fileDict.keys():
      
			element = driver.find_element(By.XPATH, "//input[@id='{}[]']".format(str(report)))
			element.send_keys(SYS2._fileDict[report])
   
		for report in SYS2._fileDict.keys():
			element = driver.find_element(By.XPATH, "//input[@onclick='verificaConteudo({})']".format(str(report))) 
			element.click()
			time.sleep(7)

    		# switch to selected iframe
			driver.switch_to.frame('ifimportacao')
			element = WebDriverWait(driver, 180).until(EC.visibility_of_element_located((By.XPATH, '/html/body/h2')))
   
			# switch back to default content
			driver.switch_to.default_content()
			element = driver.find_element(By.XPATH, '//*[@id="importacao"]/a/img')
			element.click() #close the popup
			
	def downloadFiles(driver, xpathList) -> None:
		"""
  		Given the xpath to the download buttoms, downloads all files listed

		params: 
		driver: a WebDriver instance generated by other function
		xpathList: a list of XPATH coordinates
    	"""

		for x in xpathList:
      
			element = driver.find_element(By.XPATH, x) 
			element.click()
			time.sleep(20)

	def endSession(driver):
		"""
		Ends the driver session
		"""
  
		driver.quit()

