""" 
SYS4

Módulo que acessa as funcionalidades do sistema SYS4

Author: Juliano Kosloski - Automation Developer
Created: 07/07/2022 by Juliano Kosloski
"""

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import dotenv
import os
import time

class SYS4:
    
    #internal use only
    _urlDict = { 
    "empty file path" :"empty download url"
    }

    def __getCred__(): 
        """
        Gets appropriate credentials and returns them for in-class use
        """
    
        dotenv.load_dotenv(dotenv.find_dotenv())
        sysLogin = os.environ.get("USER_SYS4")
        sysPassword = os.environ.get("PASS_SYS4")
        
        return sysLogin, sysPassword

    def startDriver():
        """
        Starts up the Chrome WebDriver config and returns a readied driver instance
        """
        
        option = webdriver.ChromeOptions()
        option.binary_location = "C:/Program Files/Google/Chrome/Application/chrome.exe"   
        driverService = Service('C:/WebDrivers/chromedriver.exe') #sets up a driver service 
        driver = webdriver.Chrome(service=driverService, options=option) #starts the driver
        return driver

    def getLogin(driver):
        """
        Takes a new driver instance and logs into a website
        
        params:
        driver: a WebDriver instance generated by other function
        """
        
        sysLogin, sysPassword = SYS4.__getCred__()
        
        driver.get("https://urlmyurl.com")
        element = driver.find_element(By.ID, "field-login" )
        element.clear()
        element.send_keys(sysLogin)
        element = driver.find_element(By.ID,"field-password" )
        element.clear()
        element.send_keys(sysPassword)
        element = driver.find_element(By.XPATH, "/html/body/div[2]/div/div[3]/div/section/div/form/div[4]/button")
        element.click()

    def downloadReports(driver, timeout = 30):
        """
        Downloads all reports listed on the in-class dictionary 'url_dict'
        
        params:
        driver: a WebDriver instance generated by other function
        timeout: time in seconds to wait for the downloads to be completed
        """
        
        for report in SYS4._urlDict:
            
            driver.get(SYS4._urlDict[report])
            element = driver.find_element(By.XPATH,"/html/body/div[2]/div/div[3]/div/article/div/section[1]/ul/li/p[1]/a[2]") #buttom "Baixar"
            element.click()

        time.sleep(timeout)
            
    def checkReports(driver) -> bool:
        """
        Check if all reports were downloaded and then ends the session
        """
        
        for path in SYS4._urlDict.keys():
            
            if os.path.exists(path) == True:
                
                print("SYS4 download sucessful.")
                driver.quit()
                return True
            
            elif os.path.exists(path) == False:
                
                print('Ocorreu um problema nos downloads!')
                driver.quit()
                return False
        
        
         

        